services:
  webapp:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "127.0.0.1:8501:8501"
    env_file: .env
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    command: ["fastapi", "run", "api.py"]
    ports:
      - "127.0.0.1:8000:8000"
    env_file: .env
    volumes:
      - type: bind
        source: ~/.aws
        target: /opt/app/.aws
